Add the SDK helpers to eval the guard config.
acuvity/acuvity-python pull request #14
Opened 2024-12-30 20:03 UTC by abhijitherekar

Issue: https://github.com/acuvity/acuvity/issues/1305

As, part of the discussion and the design doc here: https://docs.google.com/document/d/1vD1qrL3ChbhV7tLu7p6dejsEWe3oFSfE-CnNyBRB0zI/edit?tab=t.0

We will be using a guard config which the users/devs/UI can create and then eval against the response received by the backend.

2025-01-09 21:46 UTC, abhijitherekar commented on src/acuvity/verdict_processing/core/guard_processor.py
> +            comparison_result = self._threshold_helper.compare(threshold, value)
The count threshold logic is still missing in the evaluator. 

Need to add it.

2025-01-09 21:57 UTC, abhijitherekar commented on src/acuvity/apexextend.py
> +        analyzer_ids = [a.id for a in self._available_analyzers
based on this, I remebered we need to add the list of patterns that can be added to the pattern detector, basically for each detector, list all possible matches available in our solution. 

This could be a documented also, but add a API too.

2025-01-09 23:08 UTC, mheese commented on src/acuvity/apexextend.py
> +        return sorted([name for name in mapped_names if name is not None])
not sure I understand why you're changing this. It looks like you're looking for an additional list that lists the friendly names? Then this should be a separate function. The purpose of this function is to have a list of names that can be passed to analyzers during scan.

2025-01-09 23:09 UTC, mheese commented on src/acuvity/apexextend.py
> +        analyzer_ids = [a.id for a in self._available_analyzers
no, it can be documented that there is a function which lists them ;)

2025-01-09 23:13 UTC, mheese commented on src/acuvity/apexextend.py
> +        analyzers = analyzers or []
just change it on the function default then?

2025-01-09 23:17 UTC, mheese commented on src/acuvity/models/scanresponsewrapper.py
> +class ScanResponseWrapper:
I don't particularly like this class name. Can we call this something more meaningful, like `ScanResponseWithVerdict` please?

2025-01-10 00:52 UTC, mheese requested changes
The main thing that I think that we should improve is that the ScanResponseWrapper (which should also be renamed) type does not have the evaluated responses as data in them.

We know from the process of thinking through this in the document that the guardconfig matters for the request already, so we cannot simply decouple the request from the response completely (as I would have liked  to see it).

So the evaluation results of all the guards should be part of the response, and still be queryable logically too.

Apart from that, I find it quiet hard to use at the moment. the `scan()` has the guards as free form right now. While that might be a good format during parsing, we should also have an option to pass it as a typed parameter which makes it a bit easier to work with if you write them programmatically (as opposed to defining them in a config.yaml)

2025-01-11 01:53 UTC, abhijitherekar commented on src/acuvity/apexextend.py
> +        analyzers = analyzers or []
python :) It causes error if I do that, it complains about it being None.

2025-01-11 23:56 UTC, mheese commented on .speakeasy/gen.lock
>    releaseVersion: 0.4.0
please bump the release version to 0.5.0

2025-01-11 23:56 UTC, mheese commented on .speakeasy/gen.lock
>    releaseVersion: 0.4.0
you can set it manually in this file and then run `speakeasy run --skip-version` again

2025-01-12 00:01 UTC, mheese commented on src/acuvity/apexextend.py
> +        analyzers = analyzers or []
ok, makes sense ... but then you should change it back to `None` again

2025-01-12 00:02 UTC, mheese commented on src/acuvity/apexextend.py
> +        print("\n analyzer list -->", analyzers_list)
remove please

2025-01-12 00:08 UTC, mheese commented on src/acuvity/verdict_processing/constants.py
> +        }
hm, is there no way to detect that from the full analyzer object? if it's not possible or too complicated, keep it as it is.

2025-01-12 00:12 UTC, mheese commented on src/acuvity/verdict_processing/core/guard_processor.py
> +            comparison_result = self._threshold_helper.compare(threshold, value)
yes, please!

2025-01-13 20:33 UTC, abhijitherekar commented
tracking the changes here: #16

2025-01-13 20:33 UTC, closed without merging